vp0:
  container_name: vp0
  image: hyperledger/fabric-peer:x86_64-1.0.0-alpha
  ports:
    - "7050:7050"
    - "7051:7051"
    - "7052:7052"
  environment:
  - CORE_PEER_ADDRESSAUTODETECT=true
  - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
  - CORE_LOGGING_LEVEL=WARN
  - CORE_PEER_ID=vp0
  - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops
  #- CORE_PEER_LOCALMSPID=Org0MSP
  #- CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com
  #- CORE_PEER_LOCALMSPID="Org0MSP"
  #- CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/cacerts/org1.example.com-cert.pem
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    #- ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/fabric/msp/sampleconfig
  command: peer node start

vp1:
  container_name: vp1
  image: hyperledger/fabric-peer
  environment:
  - CORE_PEER_ADDRESSAUTODETECT=true
  - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
  - CORE_LOGGING_LEVEL=WARN
  - CORE_PEER_ID=vp1
  - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: peer node start
  links:
  - vp0

vp2:
  container_name: vp2
  image: hyperledger/fabric-peer
  environment:
  - CORE_PEER_ADDRESSAUTODETECT=true
  - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
  - CORE_LOGGING_LEVEL=WARN
  - CORE_PEER_ID=vp2
  - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: peer node start
  links:
  - vp0
